### PR TITLE
Update to mvvmcross v6.x

### PR DESCRIPTION
**Pull request by MrBasque**
Fully updated solution, including the Sample projects.

*Note: releasenotes untouched

### CODE REVIEW

**Comment by MrBasque** [comment]
Fully updated solution, including the Sample projects.

*Note: .nuspec files and releasenotes untouched

**Comment by Cheesebaron** [comment]
Is there any reason, you chose to reference 6.0.0 instead of latest stable MvvmCross?

**Comment by MrBasque** [comment]
> Is there any reason, you chose to reference 6.0.0 instead of latest stable MvvmCross?

Well, for compatibility actually. 
I Assumed that when the latest stable (6.2.0) is added, that would add a (nuget) dependency for >=6.2.0
and with the 6.0 package, all projects that have MvvmCross 6.0 or higher can use the component.

But, maybe my assumption is just wrong. In that case we can just add the latest stable without a problem. :)

Do you want me to add the latest stable?

**Comment by Cheesebaron** [comment]
I'd prefer just bumping it to latest stable.

**Comment by MrBasque** [comment]
> I'd prefer just bumping it to latest stable.

- Updated to latest stable for all NuGet packages.
- Updated the .nuspec files

**Comment by Cheesebaron** [comment]
Cool thanks! Will release this very soon.

**Review by Cheesebaron — APPROVED** [review]

**Pull request merged**
